app = 'open-feed-platform'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile.prod'

[mounts]
  source = 'ofa_data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
